c_compiler_version:    # [linux]
  - 11.4               # [linux]
cxx_compiler_version:  # [linux]
  - 11.4               # [linux]
MACOSX_SDK_VERSION:    # [osx]
  - 10.15              # [osx]
c_stdlib_version:      # [osx]
  - 10.15              # [osx]