c_compiler_version:    # [linux]
  - 11.4               # [linux]
cxx_compiler_version:  # [linux]
  - 11.4               # [linux]
MACOSX_SDK_VERSION:    # [osx]
  - 11.0               # [osx]
c_stdlib_version:      # [osx]
  - 11.0               # [osx]
cpu_optimization_target: nocona