{% set name = "sortmerna" %}
{% set version = "4.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6b62def30704ea956e1de060b602f9bebc8f2ba68107c59329b332500997b1d2

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - git
  host:
    - python
    - pyyaml
    - jinja2
    - requests
    - ninja
  run:
    - python

test:
  commands:
  - {{ name }} -h  # [not win]
  - {{ name }}.exe -h  # [win]

about:
  home: http://bioinfo.lifl.fr/RNA/sortmerna
  dev_url: https://github.com/sortmerna/sortmerna
  doc_url: https://sortmerna.readthedocs.io/en/latest/
  license: GPL-3.0-or-later AND LGPL-3.0-or-later
  license_file:
    - LICENSE.txt
    - LICENSE.LESSER.txt
    - RocksDB.LICENSE.Apache
    - ZLib.LICENSE
  summary: SortMeRNA is a biological sequence analysis tool for filtering, mapping and OTU-picking NGS reads.

extra:
  recipe-maintainers:
    - biocodz
